site_name: Dennis Dufrene's Portfolio
site_url: https://dennisjdufrene.github.io/dennisjdufreneportfolio/

## Publish to GitHub pages via `gh-pages`. See `publish.yml` for details.

theme:
    favicon: img/logo.png
    name: material
    logo: img/logo.png
    palette:
       scheme: default
       primary: indigo
       accent: indigo
##    features:
##      - navigation.sections

extra:
  consent:
    title: Cookie consent
    description: >- 
      My portfolio uses cookies to measure its effectiveness and whether users find what they're searching for. With your consent, you're helping me to improve my portfolio.
    actions:
      - accept
      - manage
      - reject
  analytics:
    provider: google
    property: G-QEDZ9TZX7L
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help me improve this page by
            submitting a <a href="https://github.com/DennisJDufrene/dennisjdufreneportfolio/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">Github Issue</a>.

extra_css:
    - stylesheets/extra.css

copyright: Copyright &copy; 2025 <a href="https://www.linkedin.com/in/dennisdufrene/">Dennis Dufrene</a> <br>
           Graphic icons created by <a href="https://www.flaticon.com/free-icons/graphic" title="graphic icons">Freepik - Flaticon</a> <br>
           <a href="#__consent">Change cookie settings</a>

plugins:
    - include-markdown
    - img2fig
    - search
    - macros
    - table-reader
    - render_swagger

markdown_extensions:
  - admonition
##  - fontawesome_markdown
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true


nav:
   - Home: index.md
   - About Me: about_me.md
   - Developer (Technical) Documentation:
      - Developer Documentation Overview: dev_doc_overview.md
      - API Documentation: get_user.md
      - OpenAPI (Swagger) Documentation: get_user_swagger.md
      - SDK Help File: nameservice.md
      - YAML Help: config_file.md
   - End User (Non-technical) Documentation:
      - End User Documentation Overview: enduser_doc_overview.md
      - End User Guide (PDF): user_guide.md
      - End User Guide (HTML): linuxmint.md
      - End User Help File (HTML): rss-from-source.md
      - End User Product Overview (HTML): kbin-overview.md
      - Internal Stakeholder Report (PDF): sample_report.md
      - Workflow Diagram (PDF): sample_workflow.md
   - Complete Doc Site (Semi-technical):
      - Complete Site Overview: complete-site.md
   - Process Documentation:
      - Process Documentation Overview: process_doc_overview.md
      - Technical Documentation Request Process: process_request_doc.md
      - Technical Documentation Maturity Model: tdmm.md
   - FAQ & Troubleshooting:
      - FAQ & Troubleshooting Overview: misc_docs_overview.md
      - FAQ: misc_faq.md
      - Troubleshooting: misc_trouble.md