# This is a basic workflow to help you get started with Actions

name: CI

job:
  - name: Find Old Files
  # You may pin to the exact commit or the version.
  # uses: w3f/action-find-old-files@4bf8c41bfd0bbba976afc066297c2bf59712cb1b
    uses: w3f/action-find-old-files@1.0.1
      with:
    # Stale docs min age
        minAge: 7 # default is 45
    # Comma-separated list of direcrories to look for stale files in
        dirs: # default is ["docs"]
          
