name: Check Docs Age

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  check-docs-age:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check last commit dates
        id: check_dates
        run: |
          # Get the current date in seconds since epoch
          current_date=$(date +%s)
          # Initialize an array to hold old files
          old_files=()

          # Find all files in the docs directory
          for file in $(git ls-tree -r HEAD --name-only -- docs); do
            # Get the last commit date for the file in seconds since epoch
            last_commit_date=$(git log -1 --format="%ct" -- "$file")
            # Calculate the age of the file
            age=$(( (current_date - last_commit_date) / 86400 ))  # Convert seconds to days

            # Check if the file is older than 7 days
            if [ $age -gt 7 ]; then
              old_files+=("$file")
            fi
          done

          # Check if there are any old files
          if [ ${#old_files[@]} -gt 0 ]; then
            echo "Old files found: ${old_files[@]}"
            echo "::set-output name=old_files::${old_files[*]}"
          else
            echo "No old files found."
            echo "::set-output name=old_files::"
          fi

      - name: Create GitHub Issue
        if: steps.check_dates.outputs.old_files != ''
        uses: peter-evans/create-issue@v5
        with:
          title: 'Old Documentation Files Detected'
          body: |
            The following files in the `docs` directory are older than 7 days:
            ```
            ${{ steps.check_dates.outputs.old_files }}
            ```
          labels: 'documentation, stale'
