name: Check Docs Age

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
 

jobs:
  check-docs-age:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

                  - name: Find Old Files
  # You may pin to the exact commit or the version.
  # uses: w3f/action-find-old-files@4bf8c41bfd0bbba976afc066297c2bf59712cb1b
  uses: w3f/action-find-old-files@1.0.1
  with:
    # Stale docs min age
    minAge: # default is 45
    # Comma-separated list of direcrories to look for stale files in
    dirs: # default is ["docs"]
          

                 - name: Create issues for old files
  # You may pin to the exact commit or the version.
  # uses: w3f/action-create-issues-for-old-files@1042b3f11a0aa4270e74e9028919409722417545
  uses: w3f/action-create-issues-for-old-files@1.0.1
  with:
    # List of stale files
    files: # default is staled.json
    # Issue message body
    body: # default is Last edit happened $$$ days ago 😬
    # Issue title prefix
    prefix: # default is [STALE]
    # Issue labels
    labels: # default is ["docs", "stale"]
    # Assignees list
    assignees: # optional
    # Assignees list, pick one at random
    randAssignees: # optional
    # Max issues to create per one run
    max: # default is 2
          
            The following files in the `docs` directory are older than 7 days:
            ```
            ${{ steps.check_dates.outputs.old_files }}
            ```
          labels: 'documentation, stale'
