name: Google check for old docs 

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Find old files
        id: find-old-files
        run: |
          OLD_FILES=()
          SEVEN_DAYS_AGO=$(date -d '7 days ago' +%s)
          find docs -type f -maxdepth 1 -mtime +7 -exec stat -c '%Y' {} \; | while read MODIFIED; do
              if [ "$MODIFIED" -lt "$SEVEN_DAYS_AGO" ]; then
                  OLD_FILES+=("$PWD/$(basename "$REPLY")")
              fi
          done
          echo "OLD_FILES=${OLD_FILES[*]}" >> $GITHUB_ENV

      - name: Create issue if needed
        if: steps.find-old-files.outputs.OLD_FILES != ''
        uses: actions/create-issue@v3
        with:
          issue-title: Old files found in docs directory
          issue-body: |
            The following files in the docs directory are older than 7 days:
            ```
            ${{ env.OLD_FILES }}
            ```
