name: Create Issue on Linter Failure

on:
  workflow_run:
    workflows: ['Markdown Lint Check']
    types:
      - completed

jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Create Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Markdown Linter Errors Detected',
              body: `The Markdown Linter \`${{ github.workflow }}\` has detected errors. Please investigate.

              Logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`
            })
