name: Check Markdown Files

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  check_md_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find unedited .md files
        id: find_files
        run: |
          # Set the timezone to Chicago (CST/CDT)
          export TZ="America/Chicago"

          # Get the date 7 days ago in seconds since epoch
          seven_days_ago=$(date -d '7 days ago' +%s)
          echo "Date 7 days ago: $(date -d @$seven_days_ago)"  # Debugging output

          # Initialize an empty array to hold unedited files
          unedited_files=""

          # Loop through all .md files in the docs directory
          for file in $(git ls-files docs/*.md); do
            # Get the last commit date for the file that modified its content
            last_commit_date=$(git log -1 --format="%ct" -- "$file")
            echo "File: $file, Last Commit Date: $(date -d @$last_commit_date), Timestamp: $last_commit_date"  # Debugging output
            
            # Check if the last commit date is older than 7 days
            if [ "$last_commit_date" -lt "$seven_days_ago" ]; then
              unedited_files+="$file"$'\n'
            fi
          done

          # Save the unedited files to an environment variable
          echo "unedited_files<<EOF" >> $GITHUB_ENV
          echo "$unedited_files" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create wiki page
        id: create_wiki
        run: |
          # Set the timezone to Chicago (CST/CDT)
          export TZ="America/Chicago"

          if [ -z "$unedited_files" ]; then
            echo "No unedited .md files found."
            exit 0
          fi
          # Create a new wiki page
          wiki_page="Unedited_MD_Files_$(date -d 'now' +%Y%m%d%H%M%S).md"
          echo "# Unedited Markdown Files" > "$wiki_page"
          echo "$unedited_files" >> "$wiki_page"
          git clone https://github.com/${{ github.repository }}.wiki.git wiki
          mv "$wiki_page" wiki/
          cd wiki
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add "$wiki_page"
          git commit -m "Add unedited markdown files list"
          git push

      - name: Create GitHub issue
        run: |
          if [ -z "$unedited_files" ]; then
            echo "No unedited .md files found. Skipping issue creation."
            exit 0
          fi
          # Create a new issue
          issue_title="Review Unedited Markdown Files"
          issue_body="A list of unedited markdown files has been created in the wiki: [View Wiki Page](https://github.com/${{ github.repository }}.wiki/wiki/$wiki_page)"
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues -d "{\"title\":\"$issue_title\", \"body\":\"$issue_body\"}"
