name: Markdown Lint

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v2
        id: markdownlint
        with:
          cli: 'markdownlint . --config .markdownlint.json --output markdownlint.json'
        continue-on-error: true

      - name: Print errors to file
        run: |
          if [ -s markdownlint.json ]; then
            echo "Markdown errors found:" > markdown_errors.txt
            cat markdownlint.json >> markdown_errors.txt
          else
            echo "No Markdown errors found." > markdown_errors.txt
          fi

      - name: Create issue if errors found
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if grep -q "error" markdown_errors.txt; then
            echo "Markdown errors found. Creating issue..."
            curl -X POST \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/issues \
            -H 'Authorization: Bearer $GITHUB_TOKEN' \
            -H 'Content-Type: application/json' \
            -d '{"title": "Markdown errors found", "body": "'"$(cat markdown_errors.txt)"'"}'
          fi
