name: Markdown Lint Check

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Markdown Lint Check
      id: markdown-lint
      uses: DavidAnson/markdownlint-cli2-action@v9
      continue-on-error: true
      with:
        config: .markdownlint.json
        globs: |
          **/*.md
          *.md
          docs/*.md
          docs/**/.*md
          docs/**/**/*.md
        
    - name: Check Lint Results
      run: |
        if [ -n "${{ steps.markdown-lint.outputs.results }}" ]; then
          echo "Markdown lint errors found"
          echo "${{ steps.markdown-lint.outputs.results }}"
          exit 1
        else
          echo "No Markdown lint errors found"
        fi
      
    - name: Create Issue
      if: ${{ failure() }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Markdown Lint Errors',
            body: "${{ steps.markdown-lint.outputs.results }}"
          });
