name: Markdown Lint Check

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Markdown Lint Check
      id: markdown-lint
      continue-on-error: true
      run: |
        npm install -g markdownlint-cli2
        markdownlint-cli2 --config .markdownlint.json --output-format json **/*.md *.md docs/*.md docs/**/.*md docs/**/**/*.md
      
    - name: Check Lint Results
      if: ${{ failure() }}
      run: |
        echo "Markdown lint errors found"
        echo "::set-output name=has-errors::true"
      id: check-lint
      
    - name: Create Issue
      if: ${{ steps.check-lint.outputs.has-errors == 'true' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const logs = fs.readFileSync('${{ github.workflow_job_log_url }}', 'utf8');
          
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Markdown Lint Errors',
            body: logs
          });
