name: Markdown Lint Check

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Markdown Lint Check
      id: markdown-lint
      run: |
        npm install -g markdownlint-cli2
        results=$(markdownlint-cli2 --config .markdownlint.json --output-format json **/*.md *.md docs/*.md docs/**/.*md docs/**/**/*.md)
        echo "::set-output name=results::$results"
        if [ -n "$results" ]; then
          echo "Markdown lint errors found"
          exit 1
        else
          echo "No Markdown lint errors found"
        fi
