name: Markdown Lint Check

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Markdown Lint Check
      id: markdown-lint
      run: |
        npm install -g markdownlint-cli2
        results=$(markdownlint-cli2 --config .markdownlint.json --output-format json **/*.md *.md docs/*.md docs/**/.*md docs/**/**/*.md)
        echo "::set-output name=results::$results"
        if [ -n "$results" ]; then
          echo "Markdown lint errors found"
          echo "$results"
          exit 1
        else
          echo "No Markdown lint errors found"
        fi
      
    - name: Create Issue
      if: ${{ failure() }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const results = `${{ steps.markdown-lint.outputs.results }}`;
          
          if (results.trim() !== '') {
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Markdown Lint Errors',
              body: results
            });
          }
