name: Markdown Lint Check

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Markdown Lint Check
      id: markdown-lint
      uses: DavidAnson/markdownlint-cli2-action@v9
      continue-on-error: true
      with:
        config: .markdownlint.json
        output-file: markdown-lint-results.md
        globs: |
          **/*.md
          *.md
          docs/*.md
          docs/**/.*md
          docs/**/**/*.md
        
    - name: Create Issue
      if: ${{ steps.markdown-lint.outputs.has-errors == 'true' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const results = fs.readFileSync('markdown-lint-results.md', 'utf8');
          
          if (results.trim() !== '') {
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Markdown Lint Errors',
              body: results
            });
          }
