name: Markdown Lint

on:
  push:
    branches:
      - main

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v2
        id: markdownlint
        with:
          config: '.markdownlint.json'
          format: 'json'
          output: 'markdownlint.json'

      - name: Create issue if errors found
        if: steps.markdownlint.outputs.errorCount > 0
        run: |
          echo "Markdown errors found. Creating issue..."
          curl -X POST \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/issues \
          -H 'Authorization: Bearer ${GITHUB_TOKEN}' \
          -H 'Content-Type: application/json' \
          -d '{"title": "Markdown errors found", "body": "See markdownlint.json for details"}'
