name: Markdown Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Lint Markdown Files
      uses: DavidAnson/markdownlint-cli2-action@v9
      with:
        config: .markdownlint.json
        ignore: |
          node_modules
          .github
        fix: false
        resultFile: markdownlint-results.txt
    - name: Check Markdown Lint Results
      run: |
        if [ -s markdownlint-results.txt ]; then
          echo "Markdown lint errors found:"
          cat markdownlint-results.txt
          exit 1
        else
          echo "No Markdown lint errors found."
        fi

