name: Markdown Lint

on: 
  push:
  pull_request:
  workflow_dispatch:  # Allow manual runs

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Markdown files
        id: lint
        uses: DavidAnson/markdownlint-cli2-action@v17
        continue-on-error: true
        with:
          config: '.markdownlint.json'
          globs:  |
            *.md
            docs/*.md
            **/*.md
            **/**/.*md

      - name: Capture Linting Output
        id: capture_output
        run: |
          # Capture the output of the lint step
          echo "${{ steps.lint.outputs.results }}" > lint_output.txt
          cat lint_output.txt
          if grep -q "error" lint_output.txt; then
            echo "Linting errors found."
            echo "results=$(cat lint_output.txt)" >> $GITHUB_ENV
            echo "has_errors=true" >> $GITHUB_ENV
          else
            echo "No linting errors found."
            echo "has_errors=false" >> $GITHUB_ENV
          fi

      - name: Create GitHub Issue if Linting Errors Found
        if: env.has_errors == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_TITLE="Markdown Linting Issues Found"
          ISSUE_BODY="The following issues were found in the Markdown files:\n\n\`\`\`\n${{ env.results }}\n\`\`\`"
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d "{\"title\": \"$ISSUE_TITLE\", \"body\": \"$ISSUE_BODY\", \"labels\": [\"markdown\", \"linting\"]}"
