name: Markdown Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Lint Markdown Files
      uses: DavidAnson/markdownlint-cli2-action@v9
      continue-on-error: true
      with:
        config: .markdownlint.json
        globs: |
           *.md
           **/*.md
           **/**/*.md
           **/**/**/*.md
           **/**/**/**/*.md
           
        ignore: |
          node_modules
          .github
        fix: false
