name: Monitor Docs

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  check-old-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find old commits
        id: find_old_commits
        run: |
          # Get the current date in seconds since epoch
          current_time=$(date +%s)
          # Set the threshold for 7 days (7 days * 24 hours * 60 minutes * 60 seconds)
          seven_days_ago=$((current_time - 604800))

          # Find commits older than 7 days
          old_commits=$(git log --since='7 days ago' --pretty=format:'%h - %an, %ar : %s' --reverse)

          # Check if any old commits were found
          if [ -n "$old_commits" ]; then
            echo "Old commits found:"
            echo "$old_commits"
            echo "OLD_COMMITS=$old_commits" >> $GITHUB_ENV
          else
            echo "No old commits found."
            echo "OLD_COMMITS=" >> $GITHUB_ENV
          fi

      - name: Create GitHub Issue
        if: env.OLD_COMMITS != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
        run: |
          # Prepare the issue title and body
          title="Old Commits Detected"
          body="The following commits are older than 7 days:\n\n\`\`\`\n${{ env.OLD_COMMITS }}\n\`\`\`"

          # Create the issue using GitHub API
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d "{\"title\": \"$title\", \"body\": \"$body\", \"labels\": [\"stale\"]}"
