name: Monitor Old Docs Files

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find old files
        run: |
          old_files=()
          while IFS= read -r -d '' file; do
            if [ $(find "$file" -mtime +7) ]; then
              old_files+=("$file")
            fi
          done < <(find docs/ -type f -print0)
          echo "old_files=${old_files[@]}" >> $GITHUB_ENV

      - name: Open issue if old files found
        if: env.old_files != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Old files in docs directory',
              body: 'The following files in the `docs` directory are older than seven days:\n\n${old_files[@]}'
            })
