name: Find Old Files and Update Wiki

on:
  schedule:
    - cron: '*/5 * * * *'  # This cron expression runs the workflow every 5 minutes

jobs:
  find-old-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find Old Files
        id: find_old_files
        uses: w3f/action-find-old-files@1.0.1

      - name: Write JSON to Wiki
        run: |
          echo "${{ steps.find_old_files.outputs.json }}" > old_files.json
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git clone https://github.com/${{ github.repository }}.wiki.git wiki
          cp old_files.json wiki/old_files.json
          cd wiki
          git add old_files.json
          git commit -m "Add old files JSON report"
          git push

      - name: Create Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          WIKI_URL="https://github.com/${{ github.repository }}.wiki/old_files"
          ISSUE_TITLE="Old Files Report"
          ISSUE_BODY="The old files report has been generated and can be found [here]($WIKI_URL)."
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -d "{\"title\": \"$ISSUE_TITLE\", \"body\": \"$ISSUE_BODY\"}" \
          "https://api.github.com/repos/${{ github.repository }}/issues"
