name: Old Files to Wiki

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find files older than 7 days
        id: find_old_files
        run: |
          # Find files older than 7 days and save to a variable
          OLD_FILES=$(find . -type f -mtime +7)
          echo "old_files=${OLD_FILES}" >> $GITHUB_ENV

      - name: Create a new wiki page
        id: create_wiki_page
        run: |
          if [ -n "$OLD_FILES" ]; then
            # Create a new wiki page with the old files
            WIKI_PAGE_TITLE="Old_Files_$(date +%Y%m%d%H%M%S)"
            WIKI_CONTENT="# Files older than 7 days\n\n$OLD_FILES"
            echo "$WIKI_CONTENT" > "$WIKI_PAGE_TITLE.md"
            git clone https://github.com/${{ github.repository }}.wiki.git wiki
            mv "$WIKI_PAGE_TITLE.md" wiki/
            cd wiki
            git config user.name "GitHub Action"
            git config user.email "action@github.com"
            git add "$WIKI_PAGE_TITLE.md"
            git commit -m "Add wiki page for old files: $WIKI_PAGE_TITLE"
            git push
            echo "wiki_url=https://github.com/${{ github.repository }}.wiki/wiki/$WIKI_PAGE_TITLE" >> $GITHUB_ENV
          else
            echo "No files older than 7 days."
            echo "wiki_url=" >> $GITHUB_ENV
          fi

      - name: Create an issue with the wiki link
        if: env.wiki_url != ''
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{
              "title": "Old Files Report",
              "body": "See the list of files older than 7 days [here]('${{ env.wiki_url }}')."
            }'
