name: Stale Content Reivew

on:
  schedule:
    - cron: "*/5 * * * *"
    
jobs:
  state_content_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2

      - name: Set up python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Find stale files
        run: |
          find ./docs -type f -mtime +1 > stale-content-$(date + '%Y-%m-%d').txt

      - name: Create Issue
        uses: peter-evans/create-issue-from-file@v5
        with: 
          title: Stale Content Requires Review
          content-filepath: ./stale-content-$(date +'%Y-%m-%d').txt
          labels: "documentation"
          body: "The content in the attached file must be reviewed to ensure that it is current."
     
