name: Old Files to Wiki

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find files older than 7 days
        id: find_old_files
        run: |
          # Use Python to find files older than 7 days
          echo "Checking for files older than 7 days..."
          python3 - <<EOF
import os
import time

# Get the current time
now = time.time()
# Set the threshold for 7 days
threshold = now - (7 * 86400)  # 7 days in seconds

# List to hold old files
old_files = []

# Walk through the directory
for dirpath, dirnames, filenames in os.walk('.'):
    for filename in filenames:
        filepath = os.path.join(dirpath, filename)
        # Get the last modified time
        if os.path.getmtime(filepath) < threshold:
            old_files.append(filepath)

# Print the old files
if old_files:
    print("\n".join(old_files))
else:
    print("No files older than 7 days.")
EOF
          # Capture the output into an environment variable
          OLD_FILES=$(python3 -c "
import os
import time

# Get the current time
now = time.time()
# Set the threshold for 7 days
threshold = now - (7 * 86400)  # 7 days in seconds

# List to hold old files
old_files = []

# Walk through the directory
for dirpath, dirnames, filenames in os.walk('.'):
    for filename in filenames:
        filepath = os.path.join(dirpath, filename)
        # Get the last modified time
        if os.path.getmtime(filepath) < threshold:
            old_files.append(filepath)

# Print the old files
if old_files:
    print('\n'.join(old_files))
else:
    print('')  # Print empty if no old files found
")

          echo "old_files=${OLD_FILES}" >> $GITHUB_ENV

      - name: Create a new wiki page
        id: create_wiki_page
        run: |
          if [ -n "${{ env.old_files }}" ]; then
            # Create a new wiki page with the old files
            WIKI_PAGE_TITLE="Old_Files_$(date +%Y%m%d%H%M%S)"
            WIKI_CONTENT="# Files older than 7 days\n\n${{ env.old_files }}"
            echo "$WIKI_CONTENT" > "$WIKI_PAGE_TITLE.md"
            git clone https://github.com/${{ github.repository }}.wiki.git wiki
            mv "$WIKI_PAGE_TITLE.md" wiki/
            cd wiki
            git config user.name "GitHub Action"
            git config user.email "action@github.com"
            git add "$WIKI_PAGE_TITLE.md"
            git commit -m "Add wiki page for old files: $WIKI_PAGE_TITLE"
            git push
            echo "wiki_url=https://github.com/${{ github.repository }}.wiki/wiki/$WIKI_PAGE_TITLE" >> $GITHUB_ENV
          else
            echo "No files older than 7 days."
            echo "wiki_url=" >> $GITHUB_ENV
          fi

      - name: Create an issue with the wiki link
        if: env.wiki_url != ''
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{
              "title": "Old Files Report",
              "body": "See the list of files older than 7 days [here]('${{ env.wiki_url }}')."
            }'
