name: Docs Cleanup

on:
  push:
    paths:
      - 'docs/**'
  schedule:
    - cron: '*/5 * * * *'

jobs:

  cleanup:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Find old files
      id: old_files
      run: |
        # Find files in the docs folder that are older than 7 days
        old_files=$(find docs -type f -mtime +7 -print0 | xargs -0 -I {} basename {})
        echo "::set-output name=files::$old_files"
        
    - name: Print to Wiki
      if: steps.old_files.outputs.files
      run: |
        # Create a new wiki page with the list of old files
        wiki_page="Old Docs Files"
        wiki_content=$(echo "${{ steps.old_files.outputs.files }}" | tr ' ' '\n')
        gh wiki create "$wiki_page" --copy-to-clipboard <<< "$wiki_content"
        
    - name: Create Issue
      if: steps.old_files.outputs.files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create a new issue with the link to the wiki page
        issue_title="Old Docs Files"
        issue_body="The following files in the docs folder are older than 7 days:\n\n[View Wiki Page](${{ github.server_url }}/${{ github.repository }}/wiki/$wiki_page)"
        gh issue create --title "$issue_title" --body "$issue_body"
