name: Stale Content Review

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  check-old-md-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find old .md files
        id: find_old_md
        run: |
          # Find .md files older than 7 days
          OLD_FILES=$(find . -name "*.md" -mtime +7)
          echo "old_files=$OLD_FILES" >> $GITHUB_ENV

      - name: Create wiki page
        if: env.old_files != ''
        run: |
          # Create a new wiki page with the old .md files
          WIKI_PAGE="OldMarkdownFiles.md"
          echo "# Stale Content" > $WIKI_PAGE
          echo "The following files include stale content:" >> $WIKI_PAGE
          echo "$OLD_FILES" >> $WIKI_PAGE
          
          # Commit and push the new wiki page
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git clone https://github.com/${{ github.repository }}.wiki.git wiki
          cp $WIKI_PAGE wiki/
          cd wiki
          git add .
          git commit -m "Add old markdown files list"
          git push

      - name: Create GitHub issue
        if: env.old_files != ''
        run: |
          # Create an issue with a link to the wiki page
          ISSUE_TITLE="Old Markdown Files Detected"
          ISSUE_BODY="The following .md files are older than 7 days. Please check the [OldMarkdownFiles](https://github.com/${{ github.repository }}.wiki/OldMarkdownFiles) wiki page for details."
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"title\": \"$ISSUE_TITLE\", \"body\": \"$ISSUE_BODY\"}" \
          https://api.github.com/repos/${{ github.repository }}/issues
